server:
  port: 6060
spring:
  application:
    name: server-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
  instance:
      instance-id: consumer6060
      prefer-ip-address: true